### PR TITLE
Fix playwright tests

### PR DESCRIPTION
**Pull request by JKlarlund**

### CODE REVIEW

**Review by MrBStones — COMMENTED** [review]
Looks good but tests still fail on gh actions which means we can't create a new release automatically

**Comment by MrBStones** [comment]
I think we might have to add something to our GitHub action to make it work. When it fails it says something about running a command.

**Comment by JKlarlund** [comment]
Please don't merge

**Comment by DefaultDaddy** [comment]
Looks good Jonathan. Nice work!

**Review by MrBStones — APPROVED** [review]
lgtm :+1:

**Pull request merged**
