### PR TITLE
Onion

### PR DESCRIPTION
**Pull request by FireCubeStudios**
DONT MERGE

### CODE REVIEW

**Comment by alexop1000** [comment]
IM GONNA MERGE

**Comment by FireCubeStudios** [comment]
> IM GONNA MERGE

DONT MERGE OR IM GOING TO KILL YOU

**Comment by FireCubeStudios** [comment]
Minor refactor complete, Pls review and merge

**Comment by FireCubeStudios** [comment]
WHO MERGED TO MAIN BEFORE THE REFACTOR

**Comment by PLtier** [comment]
😂

**Pull request merged**
